### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ericelliott** [jesstelford/cloverfield-build-make#1]
1. How do I watch for file changes and automatically trigger select rebuilds?
2. How do I reload the app in my browser automatically after each rebuild during the dev process?
3. Does all of this work on Windows?

**Comment by jesstelford** [comment]
> 1 How do I watch for file changes and automatically trigger select rebuilds?

Completed in e97fd3b;

``` bash
make watch-build
```

Will use the npm watch package, and spin off two processes (one watching js changes, the other watching css changes), which can be terminated with Ctrl-C.

> 2 How do I reload the app in my browser automatically after each rebuild during the dev process?

This sounds like it's outside the scope of this build-tool example. However, an approach would be to add another target:

``` Makefile
watch-js-refresh: js
    @watch "make js & refresh-browser" $(source_dir)
```

Where `refresh-browser` is some executable that handles refreshing the browser.

> 3 Does all of this work on Windows?

Honestly; no idea - I don't have a windows machine to test on unfortunately.

**Comment by ericelliott** [comment]
Thanks. =)
